### ISSUE TITLE
SSL Connect Errors due to old rubygems version

### ISSUE THREAD

**Issue by jaxxstorm** [coinbase/coinbase-exchange-ruby#17]
I'm getting the following issue when hitting the API:

```
/Users/Lee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
	from /Users/Lee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:933:in `connect'
	from /Users/Lee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/Lee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/Lee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /Users/Lee/.rvm/gems/ruby-2.3.1/gems/coinbase-exchange-0.1.2/lib/coinbase/exchange/adapters/net_http.rb:35:in `http_verb'
	from /Users/Lee/.rvm/gems/ruby-2.3.1/gems/coinbase-exchange-0.1.2/lib/coinbase/exchange/api_client.rb:285:in `get'
	from /Users/Lee/.rvm/gems/ruby-2.3.1/gems/coinbase-exchange-0.1.2/lib/coinbase/exchange/api_client.rb:55:in `last_trade'
	from check_coinbase.rb:8:in `<main>'
```

My code:

```
rest_api = Coinbase::Exchange::Client.new("redacted")

rest_api.last_trade(product_id: "BTC-GBP") do |resp|
  p "Spot Rate: £ %.2f" % resp.price
end
```

Pretty simple.

I'm on OS X with ruby 2.3.1

**Comment by jaxxstorm** [comment]
Think this is just a legacy gem issue, needs releasing to rubygems.

I added this to my Gemfile:

```
gem "coinbase-exchange", :git => "https://github.com/coinbase/coinbase-exchange-ruby.git"
```

And then ran it with bundler and it works without issue

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
